version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
resolve_s3 = true
s3_prefix = "alc"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = [
    "PdfBucketName=${env:PDF_BUCKET_NAME}",
    "BedrockInferenceProfileArn=${env:BEDROCK_INFERENCE_PROFILE_ARN}",
    "LangfuseHost=${env:LANGFUSE_HOST}",
    "LangfuseSecretUrl=${env:LANGFUSE_SECRET_URL}",
    "CognitoUserPoolId=${env:COGNITO_USER_POOL_ID}"
]
