AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: AWS Level Checker Lambda関数の定義

Parameters:
  S3BucketName:
    Type: String
    Description: PDFファイルを保存するS3バケット名
    Default: alc-uploaded-documents
  BedrockInferenceProfileArn:
    Type: String
    Description: Bedrock推論プロファイルのARN
  LangfuseHost:
    Type: String
    Description: LangfuseのホストURL
  LangfuseSecretUrl:
    Type: String
    Description: AWS Secrets ManagerのLangfuse用エンドポイントURL

# 共通設定
Globals:
  Function:
    Runtime: python3.9
    MemorySize: 128
    Timeout: 30
    # Lambdaレイヤーの設定
    Layers:
      - arn:aws:lambda:us-east-1:715841358122:layer:langfuse:5
      - arn:aws:lambda:us-east-1:177933569100:layer:AWS-Parameters-and-Secrets-Lambda-Extension:12
    # 環境変数の設定
    Environment:
      Variables:
        BEDROCK_INFERENCE_PROFILE_ARN: !Ref BedrockInferenceProfileArn
        LANGFUSE_HOST: !Ref LangfuseHost
        LANGFUSE_SECRET_URL: !Ref LangfuseSecretUrl

Resources:
  # PDFドキュメント処理用Lambda関数
  LoadDocumentFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: load_document/
      Handler: lambda_function.lambda_handler
      Description: アップロードされたPDFファイルを処理するLambda関数
      Runtime: python3.9  # PDFライブラリのため、より新しいランタイムを使用
      MemorySize: 256    # PDFの処理に必要なメモリを確保
      Timeout: 30
      Environment:
        Variables:
          AWS_REGION: us-east-1
          S3_BUCKET_NAME: !Ref S3BucketName
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - s3:PutObject
                - s3:GetObject
              Resource: !Sub 'arn:aws:s3:::${S3BucketName}/*'

  # 評価出力用Lambda関数
  EvaluateOutputFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: evaluate_output/
      Handler: lambda_function.lambda_handler
      Description: ユーザーのAWSアウトプットをレベル判定するLambda関数
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - bedrock:*
              Resource: '*'
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
                - secretsmanager:PutSecretValue
              Resource: '*'

  # ツイート生成用Lambda関数
  GenerateTweetFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: generate_tweet/
      Handler: lambda_function.lambda_handler
      Description: アウトプット判定結果をサマリーしてツイートを生成するLambda関数
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - bedrock:*
              Resource: '*'
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
                - secretsmanager:PutSecretValue
              Resource: '*'

# 出力値の定義
Outputs:
  LoadDocumentFunctionArn:
    Description: PDFドキュメント処理Lambda関数のARN
    Value: !GetAtt LoadDocumentFunction.Arn

  EvaluateOutputFunctionArn:
    Description: 評価出力Lambda関数のARN
    Value: !GetAtt EvaluateOutputFunction.Arn

  GenerateTweetFunctionArn:
    Description: ツイート生成Lambda関数のARN
    Value: !GetAtt GenerateTweetFunction.Arn
