name: デプロイ（dev環境）

on:
  push:
    branches:
      - dev

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 
      name: dev
    
    steps:
      - uses: actions/checkout@v4
      
      # フロントエンドのデプロイ
      - name: Node.jsのセットアップ
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: AWS認証情報の設定
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.IAM_ROLE_ARN }}
          aws-region: us-east-1
          role-session-name: GitHubActionsSession
          
      - name: 依存ライブラリのインストール
        working-directory: ./frontend
        run: npm install
        
      - name: ビルド
        working-directory: ./frontend
        env:
          VITE_SITE_URL: ${{ vars.VITE_SITE_URL }}
          VITE_COGNITO_DOMAIN: ${{ vars.VITE_COGNITO_DOMAIN }}
          VITE_COGNITO_AUTHORITY: ${{ vars.VITE_COGNITO_AUTHORITY }}
          VITE_COGNITO_REDIRECT_URI: ${{ vars.VITE_COGNITO_REDIRECT_URI }}
          VITE_COGNITO_LOGOUT_URI: ${{ vars.VITE_COGNITO_LOGOUT_URI }}
          VITE_API_ENDPOINT: ${{ vars.VITE_API_ENDPOINT }}
          VITE_TWEET_API_ENDPOINT: ${{ vars.VITE_TWEET_API_ENDPOINT }}
          VITE_COGNITO_CLIENT_ID: ${{ secrets.VITE_COGNITO_CLIENT_ID }}
          VITE_LANGFUSE_PUBLIC_KEY: ${{ secrets.VITE_LANGFUSE_PUBLIC_KEY }}
        run: npm run build:dev
        
      - name: S3へデプロイ
        run: |
          aws s3 sync ./frontend/dist/ s3://${{ vars.S3_BUCKET_NAME }}/ --delete
          
      - name: CloudFrontのキャッシュ削除
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ vars.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"

      # バックエンドのデプロイ
      - name: Python 3.9のセットアップ
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: SAM CLIのインストール
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      - name: SAMビルド
        working-directory: ./backend
        run: sam build

      - name: SAMデプロイ
        working-directory: ./backend
        run: |
          sam deploy --config-env dev --no-confirm-changeset --no-fail-on-empty-changeset \
            --parameter-overrides \
              BedrockInferenceProfileArn=${{ vars.BEDROCK_INFERENCE_PROFILE_ARN }} \
              LangfuseHost=${{ vars.LANGFUSE_HOST }} \
              LangfuseSecretUrl=${{ vars.LANGFUSE_SECRET_URL }}

      # Langfuseプロンプトの更新
      - name: Langfuseライブラリのインストール
        run: pip install langfuse

      - name: プロンプトの更新
        working-directory: ./prompts
        env:
          LANGFUSE_PUBLIC_KEY: ${{ secrets.LANGFUSE_PUBLIC_KEY }}
          LANGFUSE_SECRET_KEY: ${{ secrets.LANGFUSE_SECRET_KEY }}
          LANGFUSE_HOST: ${{ vars.LANGFUSE_HOST }}
        run: python update_prompts.py
